### ISSUE TITLE
Tag releases (e.g. `latest`)

### ISSUE THREAD

**Issue by iyerusad** [tpanj/cht.exe#3]
`https://api.github.com/repos/tpanj/cht.exe/releases/latest` should return latest release.

Similar to `https://api.github.com/repos/mvdan/sh/releases/latest`

**Comment by tpanj** [comment]
What are benefits for having this and how to achieve?

**Comment by iyerusad** [comment]
Just a small 'nice to have'.

**How:** Through Continous Integration (CI) - Github's form of CI is called [Releases]( https://help.github.com/en/github/administering-a-repository/releasing-projects-on-github)

**Why:** Storing binaries within a git repository is usually [not ideal](https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/), but it is not forbidden - and it is likely the lowest overhead option for a repo that doesn't regularly get changes. 

Closing this issue as current setup is least overhead and seems best suited for this project (a CI pipeline, while nice, is more overhead that is not needed for minor projects with few edits). If the project ever gets more than a handful of edits, setting up CI would be good.

**Comment by tpanj** [comment]
@iyerusad Thanks for explaining - it took me some time to achieve this with also changed programming language.
