### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by ImportTaste** [tpanj/cht.exe#9]
The last version released was over 4 years ago and compiling this and the build guide for Windows wants some very old software that isn't available anymore.

Any chance you could release a new version, maybe even set up compiling on commit via GitHub Actions?

**Comment by tpanj** [comment]
I think is possible both. Please vote on https://github.com/tpanj/cht.exe/discussions/10

**Comment by tpanj** [comment]
Done. Check https://github.com/tpanj/cht.exe/releases/
